//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buisness.Workflows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buisness.Workflows.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу выдать ТМЦ &apos;{0}&apos; номер сертификата завода изготовителя &apos;{1}&apos; остаток на котором &apos;{2}&apos; ед.изм &apos;{3}&apos; , вы просите выдать  &apos;{4}&apos; ед.изм &apos;{3}&apos; . столько нет..
        /// </summary>
        internal static string EIS_0 {
            get {
                return ResourceManager.GetString("EIS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер (сертификат завода изготовителя) необходимо сначала подтвердить.
        /// </summary>
        internal static string PCO_0 {
            get {
                return ResourceManager.GetString("PCO_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер (лицевой счет сертификата завода изготовителя) необходимо сначала подтвердить.
        /// </summary>
        internal static string PCO_1 {
            get {
                return ResourceManager.GetString("PCO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер уже частично закрыт (для выбранного сертификата завода изготовителя уже  был сформирован приходный ордер). Что бы  удалить предварительный приходный ордер (лицевой счет сертификата завода изготовителя )необходимо  перевести его в состояние  в &quot;Не потвержден&quot;.
        /// </summary>
        internal static string PCO_10 {
            get {
                return ResourceManager.GetString("PCO_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер находиться в состоянии &quot;Потвержден&quot;. Что бы  удалить предварительный приходный ордер (лицевой счет сертифифката завода изготовителя )необходимо  перевести его в состояние  в &quot;Не потвержден&quot;.
        /// </summary>
        internal static string PCO_11 {
            get {
                return ResourceManager.GetString("PCO_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер(сертифифкат завода изготовителя) находиться в состоянии &quot;Потвержден&quot;. Что бы  удалить предварительный приходный ордер (сертификат завода изготовителя )необходимо  перевести его в состояние  в &quot;Не потвержден&quot;.
        /// </summary>
        internal static string PCO_12 {
            get {
                return ResourceManager.GetString("PCO_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер (Сертификат завода изготовителя ) уже  закрыт (для выбранного сертификата завода изготовителя уже  был сформирован приходный ордер). Что бы добавить еще один лицевой счет для сертификата завода изготовителя установите статус &quot;Потвержден&quot; для выбраного сертификата завода изготовителя..
        /// </summary>
        internal static string PCO_13 {
            get {
                return ResourceManager.GetString("PCO_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер уже  закрыт (для выбранного сертификата завода изготовителя уже  был сформирован приходный ордер).  Данная возможность еще не реализована.
        /// </summary>
        internal static string PCO_14 {
            get {
                return ResourceManager.GetString("PCO_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер (лицевой счет сертификата завода изготовителя)  в состоянии &quot;Закрыт&quot;. Что бы его отредактировать необходимо перевести его в состояние &quot;Не потвержден&quot;.
        /// </summary>
        internal static string PCO_15 {
            get {
                return ResourceManager.GetString("PCO_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер (лицевой счет сертификата завода изготовителя)  в состоянии &quot;Потвержден&quot;. Что бы его отредактировать необходимо перевести его в состояние &quot;Не потвержден&quot;.
        /// </summary>
        internal static string PCO_16 {
            get {
                return ResourceManager.GetString("PCO_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу установить лицевой счет для всех сертифкатов завода изготовителя. Обнаружено что есть предварительные приходные ордера (лицевые счета  сертификата завода изготовителя) в состоянии &quot;Потвержден&quot;.   Данная возможность еще не реализована.
        /// </summary>
        internal static string PCO_17 {
            get {
                return ResourceManager.GetString("PCO_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу установить лицевой счет для всех сертифкатов завода изготовителя. Обнаружено что есть предварительные приходные ордера (лицевые счета  сертификата завода изготовителя) в состоянии &quot;Закрыт&quot;.   Данная возможность еще не реализована.
        /// </summary>
        internal static string PCO_18 {
            get {
                return ResourceManager.GetString("PCO_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер уже подтверждён товароведом. Необходимо обратиться к товароведу..
        /// </summary>
        internal static string PCO_2 {
            get {
                return ResourceManager.GetString("PCO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер (лицевой счет сертификата завода изготовителя) уже подтверждён товароведом. Необходимо обратиться к товароведу..
        /// </summary>
        internal static string PCO_3 {
            get {
                return ResourceManager.GetString("PCO_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер уже частично закрыт (есть сертификаты завода изготовителя для которых были сформированы приходный ордера). Что бы перевести предварительный приходный ордер в состояние “Не подтверждён” измените, состояние всех предварительных сертификатов завода изготовителя в состояние “Подтверждён”.
        /// </summary>
        internal static string PCO_4 {
            get {
                return ResourceManager.GetString("PCO_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер необходимо сначала подтвердить.
        /// </summary>
        internal static string PCO_5 {
            get {
                return ResourceManager.GetString("PCO_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер уже частично закрыт (для выбранного сертификата завода изготовителя уже  был сформирован приходный ордер). Что бы перевести предварительный приходный ордер (сертификат завода изготовителя) в состояние “Не подтверждён” измените, состояние всех предварительных сертификатов завода изготовителя (лицевых счетов) в состояние “Не подтверждён”.
        /// </summary>
        internal static string PCO_6 {
            get {
                return ResourceManager.GetString("PCO_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер уже частично закрыт (для выбранного сертификата завода изготовителя уже  был сформирован приходный ордер). Что бы перевести предварительный приходный ордер (лицевой счет сертификата завода изготовителя) в состояние “Не подтверждён” измените, состояние лицевого счета сертификата завода изготовителя  в состояние “Подтверждён”.
        /// </summary>
        internal static string PCO_7 {
            get {
                return ResourceManager.GetString("PCO_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер уже частично закрыт (для выбранного сертификата завода изготовителя уже  был сформирован приходный ордер). Что бы  удалить пердварительный приходный ордер необходимо  перевести его в состояние  в &quot;Не потвержден&quot;.
        /// </summary>
        internal static string PCO_8 {
            get {
                return ResourceManager.GetString("PCO_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный приходный ордер уже частично закрыт (для выбранного сертификата завода изготовителя уже  был сформирован приходный ордер) . Что бы  удалить предварительный приходный ордер (сертификат завода изготовителя )необходимо  перевести его в состояние  в &quot;Не потвержден&quot;.
        /// </summary>
        internal static string PCO_9 {
            get {
                return ResourceManager.GetString("PCO_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу определить состояние планового приходного ордера (лицевой счет сертификата завода изготовителя) {0}.
        /// </summary>
        internal static string PCOStateNotExist {
            get {
                return ResourceManager.GetString("PCOStateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу определить текущий статус у лица для согласования (список лиц для согласования) {0}.
        /// </summary>
        internal static string PMUStateNotExist {
            get {
                return ResourceManager.GetString("PMUStateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу установить сессию в переменную _session.
        /// </summary>
        internal static string PrivateFieldSessionIsNotFound {
            get {
                return ResourceManager.GetString("PrivateFieldSessionIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервиса с типом &apos;{0}&apos; не существует.
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
    }
}
