//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StateEntity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StateEntity() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.StateEntity", typeof(StateEntity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыт.
        /// </summary>
        public static string ActSelectionOfProbeStateClose {
            get {
                return ResourceManager.GetString("ActSelectionOfProbeStateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнен.
        /// </summary>
        public static string ActSelectionOfProbeStateComplete {
            get {
                return ResourceManager.GetString("ActSelectionOfProbeStateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проконтролированы Взятые пробы (представителем заказчика).
        /// </summary>
        public static string ActSelectionOfProbeStateControlCustomer {
            get {
                return ResourceManager.GetString("ActSelectionOfProbeStateControlCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проконтролированы взятые пробы.
        /// </summary>
        public static string ActSelectionOfProbeStateControlOTK {
            get {
                return ResourceManager.GetString("ActSelectionOfProbeStateControlOTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string ActSelectionOfProbeStateCreate {
            get {
                return ResourceManager.GetString("ActSelectionOfProbeStateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взять пробы.
        /// </summary>
        public static string ActSelectionOfProbeStateInitializationSampling {
            get {
                return ResourceManager.GetString("ActSelectionOfProbeStateInitializationSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не контролируется заказчиком.
        /// </summary>
        public static string ActSelectionOfProbeStateNonControlCustomer {
            get {
                return ResourceManager.GetString("ActSelectionOfProbeStateNonControlCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробы взяты.
        /// </summary>
        public static string ActSelectionOfProbeStateSamplingComplate {
            get {
                return ResourceManager.GetString("ActSelectionOfProbeStateSamplingComplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        public static string ContractStageStateAbolition {
            get {
                return ResourceManager.GetString("ContractStageStateAbolition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт.
        /// </summary>
        public static string ContractStageStateClose {
            get {
                return ResourceManager.GetString("ContractStageStateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыт.
        /// </summary>
        public static string ContractStageStateOpen {
            get {
                return ResourceManager.GetString("ContractStageStateOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утвержден.
        /// </summary>
        public static string ContractStateApproved {
            get {
                return ResourceManager.GetString("ContractStateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт.
        /// </summary>
        public static string ContractStateClose {
            get {
                return ResourceManager.GetString("ContractStateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не утвержден.
        /// </summary>
        public static string ContractStateNotApproved {
            get {
                return ResourceManager.GetString("ContractStateNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старение.
        /// </summary>
        public static string HeatTreatmentAging {
            get {
                return ResourceManager.GetString("HeatTreatmentAging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старение по КД.
        /// </summary>
        public static string HeatTreatmentAgingKD {
            get {
                return ResourceManager.GetString("HeatTreatmentAgingKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старение по ТУ.
        /// </summary>
        public static string HeatTreatmentAgingTU {
            get {
                return ResourceManager.GetString("HeatTreatmentAgingTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воздух.
        /// </summary>
        public static string HeatTreatmentCoolingAir {
            get {
                return ResourceManager.GetString("HeatTreatmentCoolingAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В печи до.
        /// </summary>
        public static string HeatTreatmentCoolingFurnace {
            get {
                return ResourceManager.GetString("HeatTreatmentCoolingFurnace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масло.
        /// </summary>
        public static string HeatTreatmentCoolingOil {
            get {
                return ResourceManager.GetString("HeatTreatmentCoolingOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вода.
        /// </summary>
        public static string HeatTreatmentCoolingWater {
            get {
                return ResourceManager.GetString("HeatTreatmentCoolingWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отпуск.
        /// </summary>
        public static string HeatTreatmentOperationAbatement {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationAbatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отжиг.
        /// </summary>
        public static string HeatTreatmentOperationAnnealing {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationAnnealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отжиг в среде аргона.
        /// </summary>
        public static string HeatTreatmentOperationArgonAnnealing {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationArgonAnnealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормализация в среде аргона.
        /// </summary>
        public static string HeatTreatmentOperationArgonNormalization {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationArgonNormalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закалка в среде аргона.
        /// </summary>
        public static string HeatTreatmentOperationArgonQuenching {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationArgonQuenching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Охлаждение.
        /// </summary>
        public static string HeatTreatmentOperationCooling {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закалка.
        /// </summary>
        public static string HeatTreatmentOperationHardening {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationHardening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нагрев.
        /// </summary>
        public static string HeatTreatmentOperationHeating {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationHeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормализация.
        /// </summary>
        public static string HeatTreatmentOperationNormalization {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationNormalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подогрев.
        /// </summary>
        public static string HeatTreatmentOperationPreheating {
            get {
                return ResourceManager.GetString("HeatTreatmentOperationPreheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка холодом.
        /// </summary>
        public static string HeatTreatmentSubzero {
            get {
                return ResourceManager.GetString("HeatTreatmentSubzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт.
        /// </summary>
        public static string PermissionMaterialExtensionStateClosed {
            get {
                return ResourceManager.GetString("PermissionMaterialExtensionStateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Согласован.
        /// </summary>
        public static string PermissionMaterialExtensionStateConfirmed {
            get {
                return ResourceManager.GetString("PermissionMaterialExtensionStateConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Согласуется.
        /// </summary>
        public static string PermissionMaterialExtensionStateConfirming {
            get {
                return ResourceManager.GetString("PermissionMaterialExtensionStateConfirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        public static string PermissionMaterialExtensionStateNew {
            get {
                return ResourceManager.GetString("PermissionMaterialExtensionStateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не согласован.
        /// </summary>
        public static string PermissionMaterialExtensionStateNotConfirmed {
            get {
                return ResourceManager.GetString("PermissionMaterialExtensionStateNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт.
        /// </summary>
        public static string PermissionMaterialStateClosed {
            get {
                return ResourceManager.GetString("PermissionMaterialStateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Согласован.
        /// </summary>
        public static string PermissionMaterialStateConfirmed {
            get {
                return ResourceManager.GetString("PermissionMaterialStateConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Согласуется.
        /// </summary>
        public static string PermissionMaterialStateConfirming {
            get {
                return ResourceManager.GetString("PermissionMaterialStateConfirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Согласуется продление.
        /// </summary>
        public static string PermissionMaterialStateConfirmingExtension {
            get {
                return ResourceManager.GetString("PermissionMaterialStateConfirmingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        public static string PermissionMaterialStateNew {
            get {
                return ResourceManager.GetString("PermissionMaterialStateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не согласован.
        /// </summary>
        public static string PermissionMaterialStateNotConfirmed {
            get {
                return ResourceManager.GetString("PermissionMaterialStateNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Согласован.
        /// </summary>
        public static string PermissionMaterialUserStateConfirmed {
            get {
                return ResourceManager.GetString("PermissionMaterialUserStateConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В ожидании.
        /// </summary>
        public static string PermissionMaterialUserStateExpecting {
            get {
                return ResourceManager.GetString("PermissionMaterialUserStateExpecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не согласован.
        /// </summary>
        public static string PermissionMaterialUserStateNotConfirmed {
            get {
                return ResourceManager.GetString("PermissionMaterialUserStateNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт.
        /// </summary>
        public static string PlanCertificateStateClose {
            get {
                return ResourceManager.GetString("PlanCertificateStateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утвержден.
        /// </summary>
        public static string PlanCertificateStateConfirm {
            get {
                return ResourceManager.GetString("PlanCertificateStateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не утвержден.
        /// </summary>
        public static string PlanCertificateStateNotСonfirm {
            get {
                return ResourceManager.GetString("PlanCertificateStateNotСonfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частично отработан.
        /// </summary>
        public static string PlanCertificateStatePartWork {
            get {
                return ResourceManager.GetString("PlanCertificateStatePartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт.
        /// </summary>
        public static string PlanReceiptOrderPersonalAccountStateClose {
            get {
                return ResourceManager.GetString("PlanReceiptOrderPersonalAccountStateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утвержден.
        /// </summary>
        public static string PlanReceiptOrderPersonalAccountStateConfirm {
            get {
                return ResourceManager.GetString("PlanReceiptOrderPersonalAccountStateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не утвержден.
        /// </summary>
        public static string PlanReceiptOrderPersonalAccountStateNotСonfirm {
            get {
                return ResourceManager.GetString("PlanReceiptOrderPersonalAccountStateNotСonfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт.
        /// </summary>
        public static string PlanReceiptOrderStateClose {
            get {
                return ResourceManager.GetString("PlanReceiptOrderStateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утвержден.
        /// </summary>
        public static string PlanReceiptOrderStateConfirm {
            get {
                return ResourceManager.GetString("PlanReceiptOrderStateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не утвержден.
        /// </summary>
        public static string PlanReceiptOrderStateNotСonfirm {
            get {
                return ResourceManager.GetString("PlanReceiptOrderStateNotСonfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частично отработан.
        /// </summary>
        public static string PlanReceiptOrderStatePartWork {
            get {
                return ResourceManager.GetString("PlanReceiptOrderStatePartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не утвержден.
        /// </summary>
        public static string QualityCertificateStateNotСonfirm {
            get {
                return ResourceManager.GetString("QualityCertificateStateNotСonfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утвержден.
        /// </summary>
        public static string QualityCertificateStateСonfirm {
            get {
                return ResourceManager.GetString("QualityCertificateStateСonfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Химический.
        /// </summary>
        public static string TestKindChemical {
            get {
                return ResourceManager.GetString("TestKindChemical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Механический.
        /// </summary>
        public static string TestKindMechanical {
            get {
                return ResourceManager.GetString("TestKindMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Металлографический.
        /// </summary>
        public static string TestKindMetallographic {
            get {
                return ResourceManager.GetString("TestKindMetallographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неразрушающий контроль.
        /// </summary>
        public static string TestKindNondestructive {
            get {
                return ResourceManager.GetString("TestKindNondestructive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт.
        /// </summary>
        public static string TestSheetStateClose {
            get {
                return ResourceManager.GetString("TestSheetStateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утвержден.
        /// </summary>
        public static string TestSheetStateConfirm {
            get {
                return ResourceManager.GetString("TestSheetStateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не утвержден.
        /// </summary>
        public static string TestSheetStateNotConfirm {
            get {
                return ResourceManager.GetString("TestSheetStateNotConfirm", resourceCulture);
            }
        }
    }
}
