//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// 08.08.2013
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace ParusModelLite.CertificateQualityDomain.ManufacturersCertificateDomain
{
    using System;
    using System.ComponentModel;

    using Halfblood.Common;

    public class CertificateQualityDestinationLiteDto :  IDto<long>
    {
        object IHasUid.Rn { get { return Rn; } }
        public virtual long Rn { get; set; }
        public virtual string Note { get; set; }
        public virtual ManufacturersCertificateDestinationState State { get; set; }
        public virtual DateTime? StateDate { get; set; }
        public virtual string Creator { get; set; }
        public virtual string UserWhichSetState { get; set; }
        public virtual string RnDestination { get; set; }
        public virtual string DestinationPass { get; set; }
        public virtual string CompactDestinationPass { get; set; }
       /* public event PropertyChangingEventHandler PropertyChanging;
        public event PropertyChangedEventHandler PropertyChanged;*/
    }
}