//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// 08.08.2013
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ParusModelLite.CertificateQualityDomain.ManufacturersCertificateDomain
{
    using System;
    using System.ComponentModel;

    using Halfblood.Common;

    public partial class CertificateQualityLiteDto : INotifyPropertyChanging, INotifyPropertyChanged, IDto<long>
    {
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private long _rn;

        private long _cRn;

        private long _rnCreator;

        private string _creator;

        private DateTime _creationDate;

        private string _marka;

        private string _cast;

        private string _fullRepresentation;
        private string _gostMarka;

        private string _gostMix;

        private DateTime _makingDate;

        private decimal _numb;

        private string _pref;

        private string _nomerCertificate;

        private long _rnCreatorFactory;

        private string _creatorFactory;

        private string _memoCreatorFactory;

        private string _note;

        private string _mix;

        private DateTime _storageDate;

        private string _memoCreator;

        private string _standardStandardSize;

        private DateTime _stateDate;

        private QualityCertificateState _state;
        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
            CertificateQualityLiteDto toCompare = obj as CertificateQualityLiteDto;
            if (toCompare == null)
            {
                return false;
            }

            if (!Object.Equals(this.Rn, toCompare.Rn))
                return false;

            return true;
        }

        public override int GetHashCode()
        {
            int hashCode = 13;
            hashCode = (hashCode * 7) + this.Rn.GetHashCode();
            return hashCode;
        }
        #endregion

        public CertificateQualityLiteDto()
        {
            this.OnCreated();
        }

        public virtual long Rn
        {
            get
            {
                return this._rn;
            }
            set
            {
                if (this._rn != value)
                {
                    this.SendPropertyChanging();
                    this._rn = value;
                    this.SendPropertyChanged("Rn");
                }
            }
        }
        public virtual long CRn
        {
            get
            {
                return this._cRn;
            }
            set
            {
                if (this._cRn != value)
                {
                    this.SendPropertyChanging();
                    this._cRn = value;
                    this.SendPropertyChanged("CRn");
                }
            }
        }
        public virtual long RnCreator
        {
            get
            {
                return this._rnCreator;
            }
            set
            {
                if (this._rnCreator != value)
                {
                    this.SendPropertyChanging();
                    this._rnCreator = value;
                    this.SendPropertyChanged("RnCreator");
                }
            }
        }
        public virtual string Creator
        {
            get
            {
                return this._creator;
            }
            set
            {
                if (this._creator != value)
                {
                    this.SendPropertyChanging();
                    this._creator = value;
                    this.SendPropertyChanged("Creator");
                }
            }
        }
        public virtual System.DateTime CreationDate
        {
            get
            {
                return this._creationDate;
            }
            set
            {
                if (this._creationDate != value)
                {
                    this.SendPropertyChanging();
                    this._creationDate = value;
                    this.SendPropertyChanged("CreationDate");
                }
            }
        }
        public virtual string Marka
        {
            get
            {
                return this._marka;
            }
            set
            {
                if (this._marka != value)
                {
                    this.SendPropertyChanging();
                    this._marka = value;
                    this.SendPropertyChanged("Marka");
                }
            }
        }
        public virtual string Cast
        {
            get
            {
                return this._cast;
            }
            set
            {
                if (this._cast != value)
                {
                    this.SendPropertyChanging();
                    this._cast = value;
                    this.SendPropertyChanged("Cast");
                }
            }
        }
        public virtual string FullRepresentation
        {
            get
            {
                return this._fullRepresentation;
            }
            set
            {
                if (this._fullRepresentation != value)
                {
                    this.SendPropertyChanging();
                    this._fullRepresentation = value;
                    this.SendPropertyChanged("FullRepresentation");
                }
            }
        }
        //==============================================================================================================================================
        private string _gostCast;
        public virtual string GostCast
        {
            get
            {
                return this._gostCast;
            }
            set
            {
                if (this._gostCast != value)
                {
                    this.SendPropertyChanging();
                    this._gostCast = value;
                    this.SendPropertyChanged("GostCast");
                }
            }
        }
        public virtual string StandardStandardSize
        {
            get
            {
                return this._standardStandardSize;
            }
            set
            {
                if (this._standardStandardSize != value)
                {
                    this.SendPropertyChanging();
                    this._standardStandardSize = value;
                    this.SendPropertyChanged("StandardStandardSize");
                }
            }
        }
        //==============================================================================================================================================
        public virtual string GostMarka
        {
            get
            {
                return this._gostMarka;
            }
            set
            {
                if (this._gostMarka != value)
                {
                    this.SendPropertyChanging();
                    this._gostMarka = value;
                    this.SendPropertyChanged("GostCast");
                }
            }
        }
        public virtual string GostMix
        {
            get
            {
                return this._gostMix;
            }
            set
            {
                if (this._gostMix != value)
                {
                    this.SendPropertyChanging();
                    this._gostMix = value;
                    this.SendPropertyChanged("GostMix");
                }
            }
        }
        public virtual DateTime MakingDate
        {
            get
            {
                return this._makingDate;
            }
            set
            {
                if (this._makingDate != value)
                {
                    this.SendPropertyChanging();
                    this._makingDate = value;
                    this.SendPropertyChanged("MakingDate");
                }
            }
        }
        public virtual decimal Numb
        {
            get
            {
                return this._numb;
            }
            set
            {
                if (this._numb != value)
                {
                    this.SendPropertyChanging();
                    this._numb = value;
                    this.SendPropertyChanged("Numb");
                }
            }
        }
        public virtual string Pref
        {
            get
            {
                return this._pref;
            }
            set
            {
                if (this._pref != value)
                {
                    this.SendPropertyChanging();
                    this._pref = value;
                    this.SendPropertyChanged("Pref");
                }
            }
        }
        public virtual string NomerCertificate
        {
            get
            {
                return this._nomerCertificate;
            }
            set
            {
                if (this._nomerCertificate != value)
                {
                    this.SendPropertyChanging();
                    this._nomerCertificate = value;
                    this.SendPropertyChanged("NomerCertificate");
                }
            }
        }
        public virtual long RnCreatorFactory
        {
            get
            {
                return this._rnCreatorFactory;
            }
            set
            {
                if (this._rnCreatorFactory != value)
                {
                    this.SendPropertyChanging();
                    this._rnCreatorFactory = value;
                    this.SendPropertyChanged("RnCreatorFactory");
                }
            }
        }
        public virtual string CreatorFactory
        {
            get
            {
                return this._creatorFactory;
            }
            set
            {
                if (this._creatorFactory != value)
                {
                    this.SendPropertyChanging();
                    this._creatorFactory = value;
                    this.SendPropertyChanged("CreatorFactory");
                }
            }
        }
        public virtual string MemoCreatorFactory
        {
            get
            {
                return this._memoCreatorFactory;
            }
            set
            {
                if (this._memoCreatorFactory != value)
                {
                    this.SendPropertyChanging();
                    this._memoCreatorFactory = value;
                    this.SendPropertyChanged("MemoCreatorFactory");
                }
            }
        }
        public virtual string Note
        {
            get
            {
                return this._note;
            }
            set
            {
                if (this._note != value)
                {
                    this.SendPropertyChanging();
                    this._note = value;
                    this.SendPropertyChanged("Note");
                }
            }
        }
        public virtual string Mix
        {
            get
            {
                return this._mix;
            }
            set
            {
                if (this._mix != value)
                {
                    this.SendPropertyChanging();
                    this._mix = value;
                    this.SendPropertyChanged("Mix");
                }
            }
        }
        public virtual DateTime StorageDate
        {
            get
            {
                return this._storageDate;
            }
            set
            {
                if (this._storageDate != value)
                {
                    this.SendPropertyChanging();
                    this._storageDate = value;
                    this.SendPropertyChanged("StorageDate");
                }
            }
        }
        public virtual string MemoCreator
        {
            get
            {
                return this._memoCreator;
            }
            set
            {
                if (this._memoCreator != value)
                {
                    this.SendPropertyChanging();
                    this._memoCreator = value;
                    this.SendPropertyChanged("MemoCreator");
                }
            }
        }
        public virtual string StandardSize
        {
            get
            {
                return this._standardStandardSize;
            }
            set
            {
                if (this._standardStandardSize != value)
                {
                    this.SendPropertyChanging();
                    this._standardStandardSize = value;
                    this.SendPropertyChanged("StandardSize");
                }
            }
        }

        public virtual DateTime StateDate
        {
            get
            {
                return this._stateDate;
            }
            set
            {
                if (this._stateDate != value)
                {
                    this.SendPropertyChanging();
                    this._stateDate = value;
                    this.SendPropertyChanged("StateDate");
                }
            }
        }
        public virtual QualityCertificateState State
        {
            get
            {
                return this._state;
            }
            set
            {
                if (this._state != value)
                {
                    this.SendPropertyChanging();
                    this._state = value;
                    this.SendPropertyChanged("StandardSize");
                }
            }
        }

        public virtual IList<CertificateQualityDestinationLiteDto> CertificateQualityDestinations { get; set; }

        object IHasUid.Rn { get { return Rn; } }

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName)
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}