//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// 08.08.2013
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace ParusModelLite.PlanReceiptOrderDomain
{
    using System;
    using System.ComponentModel;

    using Halfblood.Common;

    /// <summary>
    /// There are no comments for ParusModelLite.PlanReceiptOrderDomain.PlanCertificateLiteDto, ParusModelLite in the schema.
    /// </summary>
    public partial class PlanCertificateLiteDto : INotifyPropertyChanging, INotifyPropertyChanged, IDto<long>
    {
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private long _rn;
        private long _cRn;
        private long _prn;
        private string _note;
        private long _rnCreator;
        private string _creator;
        private PlanCertificateState _state;
        private decimal? _countByDocument;
        private decimal _countFact;
        private long? _rnStore;
        private string _store;
        private long? _rnCurrency;
        private string _currency;
        private decimal? _price;
        private DateTime? _stateDate;
        private string _memoCreator;
        private long _rnQualityCertificate;
        private System.DateTime _creationDate;
        private string _memoModifNomen;
        private long? _rnModifNomName;
        private long? _rnModifNomNameTov;
        private string _nomModifCode;
        private decimal? _sumDocumenta;
        private decimal? _sumWithTaxDocumenta;
        private string _measure;
        private string _taxBand;
        private long? _rnMeasure;
        private long? _rnTaxBand;
        private string _marka;
        private string _cast;
        private string _gostMix;
        private string _gostCast;
        private string _FullRepresentation;
        private DateTime? _makingDate;
        private string _nomerCertificata;
        private string _mix;
        private DateTime? _storageDate;
        private string _deliveryCondition;
        private string _modeThermoTreatment;
        private string _sizes;
        private string _creatorFactory;
        /// <summary>
        /// The _ numb.
        /// </summary>
        private long _numb;

        /// <summary>
        /// The _ pref.
        /// </summary>
        private string _pref;

        object IHasUid.Rn { get { return Rn; } }

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
            PlanCertificateLiteDto toCompare = obj as PlanCertificateLiteDto;
            if (toCompare == null)
            {
                return false;
            }

            if (!Object.Equals(this.Rn, toCompare.Rn))
                return false;

            return true;
        }

        public override int GetHashCode()
        {
            int hashCode = 13;
            hashCode = (hashCode * 7) + Rn.GetHashCode();
            return hashCode;
        }
        #endregion
        /// <summary>
        /// There are no comments for PlanCertificateLiteDto constructor in the schema.
        /// </summary>
        public PlanCertificateLiteDto()
        {
            OnCreated();
        }
        #region Public Properties

        /// <summary>
        /// There are no comments for Rn in the schema.
        /// </summary>
        public virtual long Rn
        {
            get
            {
                return this._rn;
            }
            set
            {
                if (this._rn != value)
                {
                    this.SendPropertyChanging();
                    this._rn = value;
                    this.SendPropertyChanged("Rn");
                }
            }
        }


        /// <summary>
        /// There are no comments for CRn in the schema.
        /// </summary>
        public virtual long CRn
        {
            get
            {
                return this._cRn;
            }
            set
            {
                if (this._cRn != value)
                {
                    this.SendPropertyChanging();
                    this._cRn = value;
                    this.SendPropertyChanged("CRn");
                }
            }
        }


        /// <summary>
        /// There are no comments for Prn in the schema.
        /// </summary>
        public virtual long Prn
        {
            get
            {
                return this._prn;
            }
            set
            {
                if (this._prn != value)
                {
                    this.SendPropertyChanging();
                    this._prn = value;
                    this.SendPropertyChanged("Prn");
                }
            }
        }


        /// <summary>
        /// There are no comments for Note in the schema.
        /// </summary>
        public virtual string Note
        {
            get
            {
                return this._note;
            }
            set
            {
                if (this._note != value)
                {
                    this.SendPropertyChanging();
                    this._note = value;
                    this.SendPropertyChanged("Note");
                }
            }
        }


        /// <summary>
        /// There are no comments for RnCreator in the schema.
        /// </summary>
        public virtual long RnCreator
        {
            get
            {
                return this._rnCreator;
            }
            set
            {
                if (this._rnCreator != value)
                {
                    this.SendPropertyChanging();
                    this._rnCreator = value;
                    this.SendPropertyChanged("RnCreator");
                }
            }
        }


        /// <summary>
        /// There are no comments for Creator in the schema.
        /// </summary>
        public virtual string Creator
        {
            get
            {
                return this._creator;
            }
            set
            {
                if (this._creator != value)
                {
                    this.SendPropertyChanging();
                    this._creator = value;
                    this.SendPropertyChanged("Creator");
                }
            }
        }


        /// <summary>
        /// There are no comments for State in the schema.
        /// </summary>
        public virtual PlanCertificateState State
        {
            get
            {
                return this._state;
            }
            set
            {
                if (this._state != value)
                {
                    this.SendPropertyChanging();
                    this._state = value;
                    this.SendPropertyChanged("State");
                }
            }
        }


        /// <summary>
        /// There are no comments for CountByDocument in the schema.
        /// </summary>
        public virtual decimal? CountByDocument
        {
            get
            {
                return this._countByDocument;
            }
            set
            {
                if (this._countByDocument != value)
                {
                    this.SendPropertyChanging();
                    this._countByDocument = value;
                    this.SendPropertyChanged("CountByDocument");
                }
            }
        }


        /// <summary>
        /// There are no comments for CountFact in the schema.
        /// </summary>
        public virtual decimal CountFact
        {
            get
            {
                return this._countFact;
            }
            set
            {
                if (this._countFact != value)
                {
                    this.SendPropertyChanging();
                    this._countFact = value;
                    this.SendPropertyChanged("CountFact");
                }
            }
        }


        /// <summary>
        /// There are no comments for RnStore in the schema.
        /// </summary>
        public virtual long? RnStore
        {
            get
            {
                return this._rnStore;
            }
            set
            {
                if (this._rnStore != value)
                {
                    this.SendPropertyChanging();
                    this._rnStore = value;
                    this.SendPropertyChanged("RnStore");
                }
            }
        }


        /// <summary>
        /// There are no comments for Store in the schema.
        /// </summary>
        public virtual string Store
        {
            get
            {
                return this._store;
            }
            set
            {
                if (this._store != value)
                {
                    this.SendPropertyChanging();
                    this._store = value;
                    this.SendPropertyChanged("Store");
                }
            }
        }


        /// <summary>
        /// There are no comments for RnCurrency in the schema.
        /// </summary>
        public virtual long? RnCurrency
        {
            get
            {
                return this._rnCurrency;
            }
            set
            {
                if (this._rnCurrency != value)
                {
                    this.SendPropertyChanging();
                    this._rnCurrency = value;
                    this.SendPropertyChanged("RnCurrency");
                }
            }
        }


        /// <summary>
        /// There are no comments for Currency in the schema.
        /// </summary>
        public virtual string Currency
        {
            get
            {
                return this._currency;
            }
            set
            {
                if (this._currency != value)
                {
                    this.SendPropertyChanging();
                    this._currency = value;
                    this.SendPropertyChanged("Currency");
                }
            }
        }


        /// <summary>
        /// There are no comments for Price in the schema.
        /// </summary>
        public virtual decimal? Price
        {
            get
            {
                return this._price;
            }
            set
            {
                if (this._price != value)
                {
                    this.SendPropertyChanging();
                    this._price = value;
                    this.SendPropertyChanged("Price");
                }
            }
        }


        /// <summary>
        /// There are no comments for StateDate in the schema.
        /// </summary>
        public virtual DateTime? StateDate
        {
            get
            {
                return this._stateDate;
            }
            set
            {
                if (this._stateDate != value)
                {
                    this.SendPropertyChanging();
                    this._stateDate = value;
                    this.SendPropertyChanged("StateDate");
                }
            }
        }


        /// <summary>
        /// There are no comments for MemoCreator in the schema.
        /// </summary>
        public virtual string MemoCreator
        {
            get
            {
                return this._memoCreator;
            }
            set
            {
                if (this._memoCreator != value)
                {
                    this.SendPropertyChanging();
                    this._memoCreator = value;
                    this.SendPropertyChanged("MemoCreator");
                }
            }
        }


        /// <summary>
        /// There are no comments for RnQualityCertificate in the schema.
        /// </summary>
        public virtual long RnQualityCertificate
        {
            get
            {
                return this._rnQualityCertificate;
            }
            set
            {
                if (this._rnQualityCertificate != value)
                {
                    this.SendPropertyChanging();
                    this._rnQualityCertificate = value;
                    this.SendPropertyChanged("RnQualityCertificate");
                }
            }
        }


        /// <summary>
        /// There are no comments for CreationDate in the schema.
        /// </summary>
        public virtual System.DateTime CreationDate
        {
            get
            {
                return this._creationDate;
            }
            set
            {
                if (this._creationDate != value)
                {
                    this.SendPropertyChanging();
                    this._creationDate = value;
                    this.SendPropertyChanged("CreationDate");
                }
            }
        }


        /// <summary>
        /// There are no comments for MemoModifNomen in the schema.
        /// </summary>
        public virtual string MemoModifNomen
        {
            get
            {
                return this._memoModifNomen;
            }
            set
            {
                if (this._memoModifNomen != value)
                {
                    this.SendPropertyChanging();
                    this._memoModifNomen = value;
                    this.SendPropertyChanged("MemoModifNomen");
                }
            }
        }


        /// <summary>
        /// There are no comments for RnModifNomName in the schema.
        /// </summary>
        public virtual long? RnModifNomName
        {
            get
            {
                return this._rnModifNomName;
            }
            set
            {
                if (this._rnModifNomName != value)
                {
                    this.SendPropertyChanging();
                    this._rnModifNomName = value;
                    this.SendPropertyChanged("RnModifNomName");
                }
            }
        }


        /// <summary>
        /// There are no comments for RnModifNomNameTov in the schema.
        /// </summary>
        public virtual long? RnModifNomNameTov
        {
            get
            {
                return this._rnModifNomNameTov;
            }
            set
            {
                if (this._rnModifNomNameTov != value)
                {
                    this.SendPropertyChanging();
                    this._rnModifNomNameTov = value;
                    this.SendPropertyChanged("RnModifNomNameTov");
                }
            }
        }


        /// <summary>
        /// There are no comments for NomModifCode in the schema.
        /// </summary>
        public virtual string NomModifCode
        {
            get
            {
                return this._nomModifCode;
            }
            set
            {
                if (this._nomModifCode != value)
                {
                    this.SendPropertyChanging();
                    this._nomModifCode = value;
                    this.SendPropertyChanged("NomModifCode");
                }
            }
        }


        public virtual decimal? SumDocumenta
        {
            get
            {
                return this._sumDocumenta;
            }
            set
            {
                if (this._sumDocumenta != value)
                {
                    this.SendPropertyChanging();
                    this._sumDocumenta = value;
                    this.SendPropertyChanged("SumDocumenta");
                }
            }
        }

        public virtual decimal? SumWithTaxDocumenta
        {
            get
            {
                return this._sumWithTaxDocumenta;
            }
            set
            {
                if (this._sumWithTaxDocumenta != value)
                {
                    this.SendPropertyChanging();
                    this._sumWithTaxDocumenta = value;
                    this.SendPropertyChanged("SumWithTaxDocumenta");
                }
            }
        }
        public virtual long? RnMeasure
        {
            get
            {
                return this._rnMeasure;
            }
            set
            {
                if (this._rnMeasure != value)
                {
                    this.SendPropertyChanging();
                    this._rnMeasure = value;
                    this.SendPropertyChanged("RnMeasure");
                }
            }
        }

        public virtual long? RnTaxBand
        {
            get
            {
                return this._rnTaxBand;
            }
            set
            {
                if (this._rnTaxBand != value)
                {
                    this.SendPropertyChanging();
                    this._rnTaxBand = value;
                    this.SendPropertyChanged("RnTaxBand");
                }
            }
        }

        public virtual string TaxBand
        {
            get
            {
                return this._taxBand;
            }
            set
            {
                if (this._taxBand != value)
                {
                    this.SendPropertyChanging();
                    this._taxBand = value;
                    this.SendPropertyChanged("TaxBand");
                }
            }
        }
        public virtual string Measure
        {
            get
            {
                return this._measure;
            }
            set
            {
                if (this._measure != value)
                {
                    this.SendPropertyChanging();
                    this._measure = value;
                    this.SendPropertyChanged("Measure");
                }
            }
        }

        public virtual string Marka
        {
            get
            {
                return this._marka;
            }

            set
            {
                if (this._marka != value)
                {
                    this.SendPropertyChanging();
                    this._marka = value;
                    this.SendPropertyChanged("Marka");
                }
            }
        }
        public virtual string Cast
        {
            get
            {
                return this._cast;
            }

            set
            {
                if (this._cast != value)
                {
                    this.SendPropertyChanging();
                    this._cast = value;
                    this.SendPropertyChanged("Cast");
                }
            }
        }
        public virtual string FullRepresentation
        {
            get
            {
                return this._FullRepresentation;
            }

            set
            {
                if (this._FullRepresentation != value)
                {
                    this.SendPropertyChanging();
                    this._FullRepresentation = value;
                    this.SendPropertyChanged("FullRepresentation");
                }
            }
        }
        public virtual string GostCast
        {
            get
            {
                return this._gostCast;
            }

            set
            {
                if (this._gostCast != value)
                {
                    this.SendPropertyChanging();
                    this._gostCast = value;
                    this.SendPropertyChanged("GostCast");
                }
            }
        }
        public virtual string GostMix
        {
            get
            {
                return this._gostMix;
            }

            set
            {
                if (this._gostMix != value)
                {
                    this.SendPropertyChanging();
                    this._gostMix = value;
                    this.SendPropertyChanged("GostMix");
                }
            }
        }
        public virtual DateTime? MakingDate
        {
            get
            {
                return this._makingDate;
            }

            set
            {
                if (this._makingDate != value)
                {
                    this.SendPropertyChanging();
                    this._makingDate = value;
                    this.SendPropertyChanged("MakingDate");
                }
            }
        }
        public virtual string NomerCertificata
        {
            get
            {
                return this._nomerCertificata;
            }

            set
            {
                if (this._nomerCertificata != value)
                {
                    this.SendPropertyChanging();
                    this._nomerCertificata = value;
                    this.SendPropertyChanged("NomerCertificate");
                }
            }
        }
        public virtual string Mix
        {
            get
            {
                return this._mix;
            }

            set
            {
                if (this._mix != value)
                {
                    this.SendPropertyChanging();
                    this._mix = value;
                    this.SendPropertyChanged("Mix");
                }
            }
        }
        public virtual DateTime? StorageDate
        {
            get
            {
                return this._storageDate;
            }

            set
            {
                if (this._storageDate != value)
                {
                    this.SendPropertyChanging();
                    this._storageDate = value;
                    this.SendPropertyChanged("StorageDate");
                }
            }
        }
        public virtual string DeliveryCondition
        {
            get
            {
                return this._deliveryCondition;
            }

            set
            {
                if (this._deliveryCondition != value)
                {
                    this.SendPropertyChanging();
                    this._deliveryCondition = value;
                    this.SendPropertyChanged("DeliveryCondition");
                }
            }
        }
        public virtual string ModeThermoTreatment
        {
            get
            {
                return this._modeThermoTreatment;
            }

            set
            {
                if (this._modeThermoTreatment != value)
                {
                    this.SendPropertyChanging();
                    this._modeThermoTreatment = value;
                    this.SendPropertyChanged("ModeThermoTreatment");
                }
            }
        }
        public virtual string Sizes
        {
            get
            {
                return this._sizes;
            }

            set
            {
                if (this._sizes != value)
                {
                    this.SendPropertyChanging();
                    this._sizes = value;
                    this.SendPropertyChanged("StandardSize");
                }
            }
        }
        public virtual string CreatorFactory
        {
            get
            {
                return this._creatorFactory;
            }

            set
            {
                if (this._creatorFactory != value)
                {
                    this.SendPropertyChanging();
                    this._creatorFactory = value;
                    this.SendPropertyChanged("CreatorFactory");
                }
            }
        }
            
        /// <summary>
        ///     There are no comments for Numb in the schema.
        /// </summary>
        public virtual long Numb
        {
            get
            {
                return this._numb;
            }

            set
            {
                if (this._numb != value)
                {
                    this.SendPropertyChanging();
                    this._numb = value;
                    this.SendPropertyChanged("Numb");
                }
            }
        }

        /// <summary>
        ///     There are no comments for Pref in the schema.
        /// </summary>
        public virtual string Pref
        {
            get
            {
                return this._pref;
            }

            set
            {
                if (this._pref != value)
                {
                    this.SendPropertyChanging();
                    this._pref = value;
                    this.SendPropertyChanged("Pref");
                }
            }
        }
        #endregion
        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName)
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
