//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 30.07.2012 10:27:20
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace DataAccessLogic.Infrastructure
{
    using Halfblood.Common;

    public class Version : IHasUid<long>
    {
        object IHasUid.Rn { get { return Rn; } }
        public virtual long Rn { get; set; }
        public virtual string Name { get; set; }
        public virtual SectionOfSystem SectionOfSystem { get; set; }
    }
}
